url: "https://nofins.com"
permalink: simple
timezone: Asia/Bangkok
template_engine: serbea

available_locales: [en]
default_locale: en
prefix_default_locale: false

collections:
  instructors:
    output: true
    sort_by: order
    name: Instructors

html_inspector_parser: nokolexbor

# Environment-specific settings
development:
  unpublished: true
